<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="io.sanctuary.bs.api.application.user.delete.DeleteUserUseCaseTest" tests="3" skipped="0" failures="0" errors="0" timestamp="2022-09-22T23:36:17" hostname="RASHID" time="0.009">
  <properties/>
  <testcase name="givenAValidUserId_whenGatewayThrows_thenShouldReturnException()" classname="io.sanctuary.bs.api.application.user.delete.DeleteUserUseCaseTest" time="0.003"/>
  <testcase name="givenAnInvalidUserId_whenCallsDeleteUser_thenShouldBeOk()" classname="io.sanctuary.bs.api.application.user.delete.DeleteUserUseCaseTest" time="0.003"/>
  <testcase name="givenAValidUserId_whenCallsDeleteUser_thenShouldBeOk()" classname="io.sanctuary.bs.api.application.user.delete.DeleteUserUseCaseTest" time="0.002"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
